### ISSUE TITLE
Error after opening 1st crate...

### ISSUE THREAD

**Issue by KultGrazer** [SlimShadys/RocketLeagueCrateOpener#1]
Hi, I Have an Error after opening the first crate and cant figure out.

[15:41:28]: Rocket League opened!
Traceback (most recent call last):
  File "C:\Users\kultg\Downloads\RocketLeagueCrateOpener-main\RocketLeagueCrateOpener-main\crateOpener.py", line 130, in <module>
    mainThread = threading.Thread(target=mainThread(ratioX, ratioY))
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kultg\Downloads\RocketLeagueCrateOpener-main\RocketLeagueCrateOpener-main\crateOpener.py", line 65, in mainThread
    pos = checkButtons(okTemplate, equipNowTemplate, threshold, ratioX, ratioY)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kultg\Downloads\RocketLeagueCrateOpener-main\RocketLeagueCrateOpener-main\utils.py", line 41, in checkButtons
    screenshot = cv2.resize(cv2.cvtColor(np.array(pyautogui.screenshot()), cv2.COLOR_RGB2GRAY), dsize=(int(2560/ratioX),int(1440/ratioY)))
                                                  ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kultg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pyautogui\__init__.py", line 228, in _couldNotImportPyScreeze
    raise PyAutoGUIException(
pyautogui.PyAutoGUIException: PyAutoGUI was unable to import pyscreeze. (This is likely because you're running a version of Python that Pillow (which pyscreeze depends on) doesn't support currently.) Please install this module to enable the function you tried to call.

You have any idea?

Greeting

**Comment by SlimShadys** [comment]
Hi! You can try and install `pyscreeze` through `pip install pyscreeze`.
Along with that, kindly update the needed libraries with the command in the README.md file.

If it still doesn't work, you're probably running a Python version where Pillow isn't properly supported (_as stated in your error_). I use Python version `3.9.7`.

Check all those things!

**Comment by farahjr** [comment]
i had the same issue today got to downgrade it to Python 3.11
